# baseURL = "https://hjkl.it/"
languageCode = "fr"
title = "Sacha Froment"
author = "Sacha Froment"
theme = "hugo_theme_hjkl.it"

# canonifyurls = true
include_toc = true

[markup.goldmark.renderer]
unsafe = true

[params]
sitename = "Sacha FROMENT"
ethAddress = "0xDfB091f812ea27Ca58e8f556B252f245660cba87"
ethQR = "/img/ethereum-qr.png"
xmrAddress = "49ETBPrD54iCKeecWjPt2hfjciSRgptXzJc29Hd8FS97AQHzThdoxE1aE4NigAf8xYDxok1iaaGKD8a6EmUwUgkgTstDaFJ"
xmrQR = "/img/xmr-qr.png"


[taxonomies]
tag = "tags"
category = "categories"
language = "languages"

[[menu.primary]]
name = "accueil"
pre = "🏡"
url = "/"
[[menu.primary]]
name = "projets"
pre = "📁"
url = "/projets/"
[[menu.primary]]
name = "à propos"
pre = "📜"
url = "/a-propos/"
